### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by Darep**
This PR:

- adds extra options, optimal defaults and comments to 01_server.tf example
- adds floating IP address example
- adds remote commend execution example

### CODE REVIEW

**Comment by tohalla** [comment]
Looking good! Would love if we additionally had one example with minimal config required

**Comment by Darep** [comment]
> Looking good! Would love if we additionally had one example with minimal config required

Thanks! Let's see if i can add that as well :)

**Comment by Darep** [comment]
Added example of minimal config now too!

**Comment by tohalla** [comment]
btw, was thinking if the numeric prefixes should be removed from the filenames, would be more clear that these are individual examples rather than parts of a shared config

**Pull request merged**
