### PR TITLE
change image (template) from public to private or from private to private

### PR DESCRIPTION
**Pull request by LordChocoBlizzBallz**
Commit message is wrong. The title of this MR is the correct description of this feature.

### CODE REVIEW

**Comment by nikohaap** [comment]
Hi,

It's nice that the new template functionality has been proceeded but it seems that there might be still some problems with the new template management handling.

Terraform gave me an error where was said that "the public image cloning failed.." and it was already removed the original storage also. So I had a running instance but not with the working "system" storage. The original instance had two storages and I tried to change from custom template into the public one.

I can try to repeat those errors tomorrow and post those error messages in here.

**Comment by nikohaap** [comment]
Ok, It would be more important to be able to update templates from private to private.
I tried this update but the Terraform crashed when I tried to change the storage id (private to private).
I was running it with the Terraform v0.11.8

```
$ terraform plan

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

upcloud_server.test: Refreshing state... (ID: xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx)

Error: Error refreshing state: 1 error(s) occurred:

* upcloud_server.test: 1 error(s) occurred:

* upcloud_server.test: upcloud_server.test: unexpected EOF

panic: runtime error: index out of range
2018-09-24T15:49:08.049+0300 [DEBUG] plugin.terraform-provider-upcloud:
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: goroutine 29 [running]:
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: github.com/UpCloudLtd/terraform-provider-upcloud/upcloud.resourceUpCloudServerRead(0xc4200ba540, 0xd77280, 0xc42000eaa8, 0xc4200ba540, 0x0)
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/go/src/github.com/UpCloudLtd/terraform-provider-upcloud/upcloud/resource_upcloud_server.go:257 +0xb34
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: github.com/UpCloudLtd/terraform-provider-upcloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4203b2770, 0xc4203285a0, 0xd77280, 0xc42000eaa8, 0xc4203b79b8, 0x4b9101, 0xbf1a00)
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/go/src/github.com/UpCloudLtd/terraform-provider-upcloud/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:355 +0x167
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: github.com/UpCloudLtd/terraform-provider-upcloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4203b31f0, 0xc420328550, 0xc4203285a0, 0x18, 0x18, 0xc4203a2640)
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/go/src/github.com/UpCloudLtd/terraform-provider-upcloud/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: github.com/UpCloudLtd/terraform-provider-upcloud/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42000d640, 0xc4203de010, 0xc4203de260, 0x0, 0x0)
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/go/src/github.com/UpCloudLtd/terraform-provider-upcloud/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: reflect.Value.call(0xc42007f3e0, 0xc4200a7178, 0x13, 0xd825ed, 0x4, 0xc420644f18, 0x3, 0x3, 0xc42007aec0, 0x20002, ...)
2018-09-24T15:49:08.050+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
2018-09-24T15:49:08.051+0300 [DEBUG] plugin.terraform-provider-upcloud: reflect.Value.Call(0xc42007f3e0, 0xc4200a7178, 0x13, 0xc420362f18, 0x3, 0x3, 0x133d170, 0xe69a40, 0xc42007bec0)
2018-09-24T15:49:08.051+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
2018-09-24T15:49:08.051+0300 [DEBUG] plugin.terraform-provider-upcloud: net/rpc.(*service).call(0xc4201b5e00, 0xc4203f0a00, 0xc4203f2bd0, 0xc4203f2be0, 0xc420175180, 0xc42000dba0, 0xbf19c0, 0xc4203de010, 0x16, 0xbf1a00, ...)
2018-09-24T15:49:08.051+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/usr/lib/go-1.10/src/net/rpc/server.go:384 +0x14e
2018-09-24T15:49:08.052+0300 [DEBUG] plugin.terraform-provider-upcloud: created by net/rpc.(*Server).ServeCodec
2018-09-24T15:49:08.052+0300 [DEBUG] plugin.terraform-provider-upcloud: 	/usr/lib/go-1.10/src/net/rpc/server.go:480 +0x43a
2018/09/24 15:49:08 [ERROR] root: eval: *terraform.EvalRefresh, err: upcloud_server.test: unexpected EOF
2018/09/24 15:49:08 [ERROR] root: eval: *terraform.EvalSequence, err: upcloud_server.test: unexpected EOF
2018/09/24 15:49:08 [TRACE] [walkRefresh] Exiting eval tree: upcloud_server.test
2018/09/24 15:49:08 [TRACE] dag/walk: upstream errored, not walking "provider.upcloud (close)"
2018/09/24 15:49:08 [TRACE] dag/walk: upstream errored, not walking "output.test ipv4_address"
2018/09/24 15:49:08 [TRACE] dag/walk: upstream errored, not walking "root"
2018-09-24T15:49:08.054+0300 [DEBUG] plugin: plugin process exited: path=/root/.terraform.d/plugins/terraform-provider-upcloud
2018/09/24 15:49:08 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-09-24T15:49:08.057+0300 [WARN ] plugin: error closing client during Kill: err="connection is shut down"




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by cancerballs** [comment]
Weird. Can you also paste the .tf file and the crash log?

**Comment by nikohaap** [comment]
Here's a crash.log file and the .tf file
<pre>

provider "upcloud" {
  # You need to set UpCloud credentials in shell environment variable
  # using .bashrc, .zshrc or similar
  # export UPCLOUD_USERNAME="Username for Upcloud API user"
  # export UPCLOUD_PASSWORD="Password for Upcloud API user"
}

resource "upcloud_server" "test" {
  zone     = "nl-lia1"
  hostname = "nikoh-testing-upc"

  cpu      = "2"
  mem      = "1024"

  # Login details
  login {
    user = "tf"

    keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZNKVSnDL5B+0DwqO04aQLmPKSy55kZ4vDNsKl2/YrI4qroICjWT0Hum89FuHv5HdEmpjWKRpyn06WLIi28C22LO5xDWUbnbsoNSiaNSC/CgKwZ/hu5fmScb0dAf+Va+KS42FEOGcSbAd36R2htRHnaLg4cgN2RjjQw8p5lfiVPl4zDtZr8+mZZKKPs6pxHY54mM5oTt+mqzfncwvnfF4tS498VY5kC4stqZAO1/A3rdP2YI7uIXP2bvQ4MSKohI9eoePTbuOCCZC7E20NA4uKxCeimGCciAusolp+1TrkDBmARF7ew/AI/X/R9d+tlZhcJ1QSx+oM9xhEuGEL6bxJ terraform@lianatech.com",
    ]

    create_password   = false
    password_delivery = "email"
  }

  storage_devices = [
    {
      # You can use both storage template names and UUIDs
      size    = 50
      action  = "clone"
      tier    = "maxiops"
      storage = "ams-template-1536655559"
    }
  ]
}
output "test ipv4_address" {
  value = "${upcloud_server.test.ipv4_address}"
}
</pre>

[crash.log](https://github.com/UpCloudLtd/terraform-provider-upcloud/files/2414739/crash.log)

**Comment by cancerballs** [comment]
Found this in the crash.log

`2018-09-24T16:43:27.655+0300 [DEBUG] plugin.terraform-provider-upcloud: 2018/09/24 16:43:27 [DEBUG] Configured storage devices in state: [map[size:10 tier:maxiops title:terraform-nikoh-testing-upc-disk-0 id:01b9f0b3-xx-xx-xx-7a61c6906bd1 address:ide:0:0 action:clone storage:testing-msa-template-1536660552 type: backup_rule:map[]]]
2018-09-24T16:43:27.656+0300 [DEBUG] plugin.terraform-provider-upcloud: 2018/09/24 16:43:27 [DEBUG] Actual storage devices on server: []
2018-09-24T16:43:27.659+0300 [DEBUG] plugin.terraform-provider-upcloud: panic: runtime error: index out of range`

It looks like there was no storage attached to the server.

So I managed to reproduce the bug by creating a server using the TF file, then I stopped the server in the control panel, detached the storage and executed terraform plan/apply and got the exact stack trace.

Can you verify the server has a storage attached to it when executing the plan?

**Comment by nikohaap** [comment]
Yep, I just noticed the same thing. The storage was destroyed while I was trying to change it

**Comment by cancerballs** [comment]
I can't manage to reproduce this bug. Could you please try again?

**Comment by nikohaap** [comment]
1.) Create a custom template by the Packer
2.) Use the created custom template's id as a storage id for the upcloud_server resource
3.) $ terrafrom init && terrafrom apply
4.) Create a new custom template by The Packer
5.) Update the upcloud_server resource's storage id to match with the latest created template id 

I have updated the storage template id manually

**Comment by cancerballs** [comment]
I followed the steps using the example TF file provided, in the same zone and with private templates generated with packer. It worked. No crashes, no errors.

It seems to me this might be a problem you should take up with UpCloud support. There you can share the relevant UUIDs and they have tools to properly look into it.

**Pull request closed without merging**
